server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@${EUREKA_SERVER:localhost}:8761/eureka

spring:
  application:
    name: authentication-service

endpoint.login=${AUTHENTICATION_SERVICE}/api/authenticaion/login