spring:
  application:
    name: discovery-server

  cloud:
    config:
      enabled: false

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
server:
  port: 8761
