spring:
  cloud:
    config:
      enabled: false
  client:
    service-url:
      defaultZone: http://eureka:password@${eureka_server}/eureka

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost