spring:
  application:
    name: discovery-server

  cloud:
    config:
      enabled: false

  config:
    import: optional:http://localhost:8081/discovery-app.properties

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
server:
  port: 8761
